### PR TITLE
Fix IndexFactory.writeIndex for tabix indexes

### LINKED ISSUE #430: IndexFactory.writeIndex is incorrect for tabix indexes, missing BlockCompressedOutputStream
IndexFactory.writeIndex is incorrect for tabix indexes (does not use BlockCompressedOutputStream) and thus loading the index will blow up (reading does use BlockCompressedInoutStream).

Courtesy of @droazen, we know that compressing the index is indeed the right thing:
"the tbi index itself is supposed to be block compressed. Cf., eg., the code for writing tbi indices in htslib (https://github.com/samtools/htslib/blob/1e2ed48935a58845cecb64880e8cf7553c7db852/hts.c):

    } else if (fmt == HTS_FMT_TBI) {
        BGZF *fp = bgzf_open(fnidx, "w");
        if (fp == NULL) return -1;
        bgzf_write(fp, "TBI\1", 4);
        hts_idx_save_core(idx, fp, HTS_FMT_TBI);
        bgzf_close(fp);
"

gatk has a workaround: https://github.com/broadinstitute/gatk/pull/1422

### PR DESCRIPTION
**Pull request by magicDGS**

### CODE REVIEW

File: src/main/java/htsjdk/tribble/index/IndexFactory.java [hunk 1]
```diff
@@ -292,7 +294,9 @@ public static LinearIndex createLinearIndex(final File inputFile, final FeatureC
     public static void writeIndex(final Index idx, final File idxFile) throws IOException {
         LittleEndianOutputStream stream = null;
         try {
-            stream = new LittleEndianOutputStream(new BufferedOutputStream(new FileOutputStream(idxFile)));
+            final OutputStream underlyingStream = (idx instanceof TabixIndex) ?
+                    new BlockCompressedOutputStream(idxFile) : new FileOutputStream(idxFile);
```
Comment (yfarjoun) [inline src/main/java/htsjdk/tribble/index/IndexFactory.java]: would it be possible for the index to know what type of outputstream it needs and either open it for the factory, or write itself to that stream (given a file). it seems that it's more appropriate to give that decision to the index rather than to the factory.

also: tests please.

Comment (magicDGS) [inline src/main/java/htsjdk/tribble/index/IndexFactory.java]: I was thinking about this before, because actually it makes more sense to have a `Index.write(File idxFile)` method instead of the factory. But I decided to go for this to maintain compatibility. In addition, the javadoc said that "It is the responsibility of this class to determine and create the correct index type from the input file or stream.", so that's why I did it like this.

**Comment by magicDGS** [comment]
@yfarjoun, I don't know how to do tests for checking this...

File: src/main/java/htsjdk/tribble/index/Index.java [hunk 2]
```diff
@@ -26,6 +26,7 @@
 import htsjdk.tribble.util.LittleEndianOutputStream;
 
 import java.io.File;
+import java.io.FileNotFoundException;
```
Comment (yfarjoun) [inline src/main/java/htsjdk/tribble/index/Index.java]: where is this used?

File: src/main/java/htsjdk/tribble/index/AbstractIndex.java [hunk 3]
```diff
@@ -25,6 +25,7 @@
 
 import java.io.BufferedOutputStream;
 import java.io.File;
+import java.io.FileNotFoundException;
```
Comment (yfarjoun) [inline src/main/java/htsjdk/tribble/index/AbstractIndex.java]: doesn't seem to be used

**Comment by yfarjoun** [comment]
couldn't you test that you can write to a file (and an index is created) and write to a stream (and no exception is thrown)?

**Comment by magicDGS** [comment]
@yfarjoun, I added a test to assert that `write(File idxFile)` is writing a file, and that `write( LittleEndianOutputStream stream)` to a null stream is not throwing an error. This was done for both `LinearIndex` and `TabixIndex`. Are they enough?

**Comment by magicDGS** [comment]
I also squashed the commits. I think that now that the writing to the file is inside the index, the method `IndexFatory.writeIndex(final Index idx, final File idxFile)` could be deprecated. If someone already have the index file, `idx.write(idxFile)` could be used...

**Comment by magicDGS** [comment]
Can you have a look to this, @yfarjoun? It is important for other PR that I'm preparing...

**Comment by magicDGS** [comment]
Could you have a look, @yfarjoun? Thanks in advance!

File: src/main/java/htsjdk/tribble/index/AbstractIndex.java [hunk 4]
```diff
@@ -343,13 +343,20 @@ public void write(final LittleEndianOutputStream stream) throws IOException {
...
 
     @Override
-    public void writeBasedOnFeatureFile(final File featureFile) throws IOException {
-        if (!featureFile.isFile()) return;
+    public void write(final File idxFile) throws IOException {
         final LittleEndianOutputStream idxStream =
-                new LittleEndianOutputStream(new BufferedOutputStream(new FileOutputStream(Tribble.indexFile(featureFile))));
-        write(idxStream);
-        idxStream.close();
+                new LittleEndianOutputStream(new BufferedOutputStream(new FileOutputStream(idxFile)));
```
Comment (yfarjoun) [inline src/main/java/htsjdk/tribble/index/AbstractIndex.java]: extra indent?

**Comment by yfarjoun** [comment]
@lbergelson could you take a look? we originally reviewed this together.

File: src/main/java/htsjdk/tribble/index/AbstractIndex.java (hunk 4 above)
Comment (magicDGS) [inline src/main/java/htsjdk/tribble/index/AbstractIndex.java]: It comes from the previous version, but I've just put everything in a single line.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java [hunk 5]
```diff
@@ -112,4 +117,45 @@ public void testCreateTabixIndexOnBlockCompressed() {
                     "Tabix indexed (bgzipped) VCF does not contain sequence: " + samSequenceRecord.getSequenceName());
         }
     }
+
+    @Test
+    public void testWriteIndex() throws Exception {
+        // temp directory for this test
+        final File tempDir = IOUtil.createTempDir("writeIndex", null);
```
Comment (lbergelson) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: I think the standard in htsjdk is to use `File output = File.createTempFile()` to get your output file, and then call `output.deleteOnExit()` to make sure it's cleaned up afterwards.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java [hunk 6]
```diff
@@ -112,4 +117,45 @@ public void testCreateTabixIndexOnBlockCompressed() {
                     "Tabix indexed (bgzipped) VCF does not contain sequence: " + samSequenceRecord.getSequenceName());
         }
     }
+
+    @Test
+    public void testWriteIndex() throws Exception {
```
Comment (lbergelson) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: Since this test is in indexFactory.writeIndex() it should probably be testing `indexFactory.writeIndex()`...  

Test for `write` on the index files themselves should live in TabixIndexTest and LinearIndexTest respectively. 

Either way (or both might be the best at the risk of redundantly testing things), `TabixIndexTest.readWriteTest` provides a good model for how the test might be made.  Instead of repeating the code for the different cases you can write a test function that takes a dataprovider with several inputs.  It might be a pain though for linear indexes since I don't see a read or equals method on them.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java [hunk 7]
```diff
@@ -112,4 +117,45 @@ public void testCreateTabixIndexOnBlockCompressed() {
...
+        // write to an stream does not thrown an error
+        linearIndex.write(new LittleEndianOutputStream(nullOutputStrem));
+
+        // TABIX INDEX
+        final File inputFileVcfGz =
+                new File("src/test/resources/htsjdk/tribble/tabix/testTabixIndex.vcf.gz");
+        final TabixIndex tabixIndexVcfGz =
+                IndexFactory
+                        .createTabixIndex(inputFileVcfGz, new VCFCodec(), TabixFormat.VCF, null);
+        // wirte to a file
```
Comment (lbergelson) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: typo wirte -> write

File: src/main/java/htsjdk/tribble/index/AbstractIndex.java [hunk 8]
```diff
@@ -343,13 +343,19 @@ public void write(final LittleEndianOutputStream stream) throws IOException {
     }
 
     @Override
+    public void write(final File idxFile) throws IOException {
```
Comment (magicDGS) [inline src/main/java/htsjdk/tribble/index/AbstractIndex.java]: Done

File: src/main/java/htsjdk/tribble/index/IndexFactory.java [hunk 9]
```diff
@@ -290,16 +287,7 @@ public static LinearIndex createLinearIndex(final File inputFile, final FeatureC
      * @throws IOException
      */
     public static void writeIndex(final Index idx, final File idxFile) throws IOException {
```
Comment (magicDGS) [inline src/main/java/htsjdk/tribble/index/IndexFactory.java]: Done

File: src/main/java/htsjdk/tribble/index/tabix/TabixIndex.java [hunk 10]
```diff
@@ -201,6 +201,7 @@ public TabixFormat getFormatSpec() {
      *
      * @param tabixFile Where to write the index.
      */
+    @Override
     public void write(final File tabixFile) {
```
Comment (magicDGS) [inline src/main/java/htsjdk/tribble/index/tabix/TabixIndex.java]: Done. Now throwing `IOException`

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java (hunk 6 above)
Comment (magicDGS) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: I changed exactly the same method (with a data provider instead) to `IndexTest`, because I think that it could live in that package (it is testing the interface method for different implementations).

I added a check for the sequence names and properties loaded and written, and a test bed file too.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java (hunk 5 above)
Comment (magicDGS) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: I change it in the new test.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java (hunk 7 above)
Comment (magicDGS) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: Changed in the new test.

**Comment by magicDGS** [comment]
Addressed comments, @lbergelson. I changed the method to throw `IOException`, although I'm waiting for @yfarjoun comments about it.

Now that I'm looking at the tribble package, I that an issue should be open to review exceptions thrown by the classes. It will be useful for distinguish them. For instance, when I implemented `getTabixFormat()` it throws a generic `TribbleException`, but I can create another extension of the class that will be more informative.

**Comment by magicDGS** [comment]
Tests are failing for FTP issues, @yfarjoun and @lbergelson...

**Comment by lbergelson** [comment]
@magicDGS I restarted the tests.  I hate those ftp tests. 

This gets my approval.  This is a breaking change with the changes to the exceptions, but I think it's a positive one to make them more consistent.  Lets hear what @yfarjoun thinks before merging though. 

I agree with you that the current state of exceptions is pretty random.  It would be good to do an overhaul of them.

File: src/test/java/htsjdk/tribble/index/IndexFactoryTest.java (hunk 6 above)
Comment (lbergelson) [inline src/test/java/htsjdk/tribble/index/IndexFactoryTest.java]: Good decision 👍

**Comment by yfarjoun** [comment]
a strange test is failing again. otherwise 👍

**Comment by lbergelson** [comment]
Oh yeah, that one.  #578 strikes again. Restarted.

**Comment by magicDGS** [comment]
Thanks for review and accept this change, @yfarjoun and @lbergelson. I also opened an issue to have a look to the exceptions thrown in the package.
