### PR TITLE
re-enable reading bam files from pipes

### LINKED ISSUE #1083: opening a SamReader on a named pipe is broken in 2.14.2
#1077 caused a regression that prevents opening names pipes with SamReaderFactory.

The issue is the `eof()` makes a call to `RandomAccessFile.length()` which causes a failure in native code if the input file isn't actually a randomly accessible file...  For some reason we're opening named pipes as if they were seekable, which now explodes on the first read because we are calling `length()` as part of available.

The fix should be to not open named pipes as seekable inputs.

### PR DESCRIPTION
**Pull request by lbergelson**
fixing an issue that prevented reading a bam file from an unseekable file, ex: a unix pipe
fixes #1083 which was introduced by #1077

this only fixes the case where the bam is being opened as file, a similar issue exists for Paths, #1084
support for reading pipes as paths has never worked
### Checklist

- [ ] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

File: src/main/java/htsjdk/samtools/SamInputResource.java [hunk 1]
```diff
@@ -335,7 +347,7 @@ public URL asUrl() {
 
     @Override
     public SeekableStream asUnbufferedSeekableStream() {
-        return lazySeekableStream.get();
+            return lazySeekableStream.get();
```
Comment (jacarey) [inline src/main/java/htsjdk/samtools/SamInputResource.java]: extra whitespace

File: src/main/java/htsjdk/samtools/SamInputResource.java [hunk 2]
```diff
@@ -269,12 +266,27 @@ public URL asUrl() {
...
+        } else {
+            return null;
+        }
     }
 
     @Override
     public InputStream asUnbufferedInputStream() {
-        return asUnbufferedSeekableStream();
+        final SeekableStream seekableStream = asUnbufferedSeekableStream();
+        if( seekableStream != null) {
```
Comment (jacarey) [inline src/main/java/htsjdk/samtools/SamInputResource.java]: space after if and not before seekableStream

File: src/main/java/htsjdk/samtools/SamInputResource.java [hunk 3]
```diff
@@ -269,12 +266,27 @@ public URL asUrl() {
 
     @Override
     public SeekableStream asUnbufferedSeekableStream() {
-        return lazySeekableStream.get();
+        //if the file doesn't exist, the try to open the stream anyway because users might be expecting the exception
+        //if it not a regular file than we won't be able to seek on it, so return null
+        if(!fileResource.exists() || fileResource.isFile()) {
```
Comment (jacarey) [inline src/main/java/htsjdk/samtools/SamInputResource.java]: space after if
