### PR TITLE
Fix bug when loading indexed bgzip fasta file.

### LINKED ISSUE #1290: BlockCompressedIndexedFastaSequenceFile checks for a gzi even if an index is passed in.
It looks like ` new BlockCompressedIndexedFastaSequenceFile( Path, FastaSequenceIndex, GZIIndex)` inappropriately `Files.exists(GZIIndex.resolveIndexNameForBgzipFile(path)` even though the GZIIndex has been preloaded and passed in as part of `canCreateBlockCompresedIndexedFastaSequence`

### PR DESCRIPTION
**Pull request by lbergelson**
* There was a bug that prevented loading an indexed bgzip fasta file if the index location was specified but wasn't next to the fasta in the file system.
* Fixes #1290

### Checklist

- [ ] Code compiles correctly
- [ ] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

File: src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java [hunk 1]
```diff
@@ -103,12 +97,14 @@ private static GZIIndex loadFastaGziIndex(final Path path) {
         }
     }
 
-    private static boolean canCreateBlockCompresedIndexedFastaSequence(final Path path) {
+    private static void assertIsBlockCompressed(final Path path) {
         try {
             // check if the it is a valid block-compressed file and if the .gzi index exits
-            return IOUtil.isBlockCompressed(path, true) && Files.exists(GZIIndex.resolveIndexNameForBgzipFile(path));
+            if(!IOUtil.isBlockCompressed(path, true)){
```
Comment (pshapiro4broad) [inline src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java]:
```suggestion
            if (!IOUtil.isBlockCompressed(path, true)) {
```

File: src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java [hunk 2]
```diff
@@ -103,12 +97,14 @@ private static GZIIndex loadFastaGziIndex(final Path path) {
...
+              throw new SAMException("Invalid block-compressed Fasta file: " + path);
```
Comment (pshapiro4broad) [inline src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java]:
```suggestion
                throw new SAMException("Invalid block-compressed Fasta file: " + path);
```

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java [hunk 3]
```diff
@@ -27,10 +27,7 @@
 import htsjdk.HtsjdkTest;
 import htsjdk.samtools.SAMException;
 import htsjdk.samtools.seekablestream.SeekableFileStream;
-import htsjdk.samtools.util.CloserUtil;
-import htsjdk.samtools.util.GZIIndex;
-import htsjdk.samtools.util.RuntimeIOException;
-import htsjdk.samtools.util.StringUtil;
+import htsjdk.samtools.util.*;
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]: I think we should avoid using `*` imports as it makes it harder to see which package an import came from outside of an IDE. There's an IDE setting that will automatically fix this when adding/removing imports.

File: src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java [hunk 4]
```diff
@@ -103,12 +97,14 @@ private static GZIIndex loadFastaGziIndex(final Path path) {
         }
     }
 
-    private static boolean canCreateBlockCompresedIndexedFastaSequence(final Path path) {
+    private static void assertIsBlockCompressed(final Path path) {
         try {
             // check if the it is a valid block-compressed file and if the .gzi index exits
-            return IOUtil.isBlockCompressed(path, true) && Files.exists(GZIIndex.resolveIndexNameForBgzipFile(path));
```
Comment (pshapiro4broad) [inline src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java]: Is the presence of the index file asserted elsewhere? Or is it not required as we've already asserted `gziIndex != null`?

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java [hunk 5]
```diff
@@ -39,13 +36,17 @@
...
+import java.nio.file.Path;
+import java.nio.file.StandardCopyOption;
 
 /**
  * Test the indexed fasta sequence file reader.
  */
 public class AbstractIndexedFastaSequenceFileTest extends HtsjdkTest {
     private static final File TEST_DATA_DIR = new File("src/test/resources/htsjdk/samtools/reference");
     private static final File SEQUENCE_FILE = new File(TEST_DATA_DIR,"Homo_sapiens_assembly18.trimmed.fasta");
+    private static final File SEQUENCE_FILE_DICT = new File(TEST_DATA_DIR,"Homo_sapiens_assembly18.trimmed.dict");
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]: New field is unused in this PR, is that intentional? If so, you may want to add a comment as to why it's defined here so it's not deleted later on.

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java [hunk 6]
```diff
@@ -353,4 +354,16 @@ public void testBadInputForIndexedFastaSequenceFile() throws Exception {
     public void testBadInputForBlockCompressedIndexedFastaSequenceFile() throws Exception {
         new BlockCompressedIndexedFastaSequenceFile(SEQUENCE_FILE.toPath());
     }
+
+    @Test
+    public void testCanCreateBlockCompressedIndexedWithSpecifiedGZIAndDict() throws IOException {
+        final Path moved = Files.createTempFile("moved", ".fasta.gz");
+        Files.copy(SEQUENCE_FILE_BGZ.toPath(), moved, StandardCopyOption.REPLACE_EXISTING);
+        IOUtil.deleteOnExit(moved);
+        try( ReferenceSequenceFile withNoAdacentIndex = new BlockCompressedIndexedFastaSequenceFile(moved, new FastaSequenceIndex(SEQUENCE_FILE_INDEX), GZIIndex.loadIndex(SEQUENCE_FILE_GZI.toPath()));
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]:
```suggestion
        try (ReferenceSequenceFile withNoAdacentIndex = new BlockCompressedIndexedFastaSequenceFile(moved, new FastaSequenceIndex(SEQUENCE_FILE_INDEX), GZIIndex.loadIndex(SEQUENCE_FILE_GZI.toPath()));
```

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java [hunk 7]
```diff
@@ -353,4 +354,16 @@ public void testBadInputForIndexedFastaSequenceFile() throws Exception {
...
+             ReferenceSequenceFile withFilesAdjacent = new BlockCompressedIndexedFastaSequenceFile(SEQUENCE_FILE_BGZ.toPath())){
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]: Indent looks wrong on this line but it's hard to tell for sure in the PR. I would expect it to line up with the text after the `(` on the previous line.

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java [hunk 8]
```diff
@@ -353,4 +354,16 @@ public void testBadInputForIndexedFastaSequenceFile() throws Exception {
...
+            Assert.assertEquals(withNoAdacentIndex.getSubsequenceAt("chrM", 100, 1000).getBases(),
+            withFilesAdjacent.getSubsequenceAt("chrM", 100, 1000).getBases());
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]:
```suggestion
                withFilesAdjacent.getSubsequenceAt("chrM", 100, 1000).getBases());
```

File: src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java (hunk 4 above)
Comment (lbergelson) [reply src/main/java/htsjdk/samtools/reference/BlockCompressedIndexedFastaSequenceFile.java]: Yeah, the check for gziIndex != null is the correct one here.  The bug was that this was checking for an index next to your file even if you passed in one that was somewhere else.

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java (hunk 5 above)
Comment (lbergelson) [reply src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]: good catch, it was used in an earlier version of the test but it turned out to be unecessary

File: src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java (hunk 7 above)
Comment (lbergelson) [reply src/test/java/htsjdk/samtools/reference/AbstractIndexedFastaSequenceFileTest.java]: It's lined up with the beginning of the other ReferenceSequenceFile, so it's 1 space after the `(` I think it's what you expect.  Auto format doesn't change anything.

**Comment by lbergelson** [comment]
@pshapiro4broad Thanks for the review!
