### PR TITLE
Fix bug in BlockCompressedInputStream.checkTermination()

### LINKED ISSUE #1251: BlockCompressedInputStream.readFully seems likely to be buggy
My implementation of `BlockCompressedInputStream.readFully` seems like it will potentially incorrectly throw on channels that don't always provide all requested bytes when reading, it should probably read in a loop until 0 bytes are read and maybe needs to assert that the channel is in synchronous mode as well.

I'm not sure what I was thinking when I wrote it, maybe I looked deeper and found an explanation for why it's ok which I've now forgotten.

It should either be changed or documented better to explain why it's ok.

### PR DESCRIPTION
**Pull request by lbergelson**
* Fixing a bug in BlockCompressedInputStream.checkTermination()
  The internal method readFully would throw in cases where less bytes were read than were available in the stream.
  We haven't observed this in practice but it's a valid behavior of SeekableByteChannel.read() so we should honor it.
* Fixes #1251

### Description

Please explain the changes you made here.
Explain the **motivation** for making this change. What existing problem does the pull request solve?

### Checklist

- [x] Code compiles correctly
- [x] New tests covering changes and new functionality
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Is not backward compatible (breaks binary or source compatibility)

### CODE REVIEW

File: src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java [hunk 1]
```diff
@@ -692,9 +692,14 @@ public static FileTermination checkTermination(SeekableByteChannel channel) thro
      * @throws EOFException if channel has fewer bytes available than dst's capacity
      */
     static void readFully(SeekableByteChannel channel, ByteBuffer dst) throws IOException {
-        final int bytesRead = channel.read(dst);
-        if (bytesRead < dst.capacity()){
-            throw new EOFException();
+        int totalBytesRead = 0;
```
Comment (pshapiro4broad) [inline src/main/java/htsjdk/samtools/util/BlockCompressedInputStream.java]: Please reformat using IDE to fix whitespace, in all three files.

File: src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java [hunk 2]
```diff
@@ -120,6 +120,35 @@ public void testReadFullyThrowWhenItCantReadEnough() throws IOException {
...
     }
 
+    @Test
+    public void testReadFullyReadsBytesCorrectlyWhenPartialReadOccurs() throws IOException {
+        final byte[] expected = "something to test reading from".getBytes();
+        final ByteBuffer buffer = ByteBuffer.wrap(expected);
+        try(final SeekableByteChannel channel = new OneByteAtATimeChannel(buffer)){
+            final int readBufferSize = 10;
+            final ByteBuffer readBuffer = ByteBuffer.allocate(readBufferSize);
+           // Assert.assertTrue(channel.size() >= readBuffer.capacity());
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java]: Delete or uncomment commented code

File: src/test/java/htsjdk/samtools/SeekableByteChannelFromBuffer.java [hunk 3]
```diff
@@ -77,6 +77,10 @@ public void close() throws IOException {
     open = false;
   }
 
+  protected ByteBuffer getBuffer(){
```
Comment (pshapiro4broad) [inline src/test/java/htsjdk/samtools/SeekableByteChannelFromBuffer.java]: Seems a shame to expose this for testing purposes only.  If the subclass type was defined in the same package, you could use package (default) scope instead, which is more restrictive than protected, and doesn't lead to API compatibility requirements later on.

So you could use default scope here if you defined `OneByteAtATimeChannel` in the same package as `SeekableByteChannelFromBuffer`. You could put the source in the test directory so it wouldn't be part of the public API.

Comment (lbergelson) [reply src/test/java/htsjdk/samtools/SeekableByteChannelFromBuffer.java]: This class is already in the test directories so it isn't part of the public API.  I don't mind moving them both to a subpackage though and restricting it to default scope.

Comment (lbergelson) [reply src/test/java/htsjdk/samtools/SeekableByteChannelFromBuffer.java]: moved both to htsjdk.testutil.streams

File: src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java (hunk 2 above)
Comment (lbergelson) [reply src/test/java/htsjdk/samtools/util/BlockCompressedTerminatorTest.java]: done
